const mockProducts = [
    {
        id: "1",
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        price: '1699.99',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        memory: ["256GB", "512GB", "1TB", "2TB"],

        itemImageUrl: '/images/test/iphone14.png',
        brand: 'Apple',
    },
    {
        id: "2",
        name: "Apple AirPods Max",
        description: "Silver",
        price: "549.99",
        availableColors: ["#C0C0C0"],
        itemImageUrl: "/images/test/iphone14.png",
        memory: ["256GB", "512GB", "1TB", "2TB"],

        brand: "Apple",
    },
    {
        id: "3",
        name: "Apple iPhone 15 Pro",
        description: "256GB Gray (MQ9T3RX/A)",
        price: "1799.99",
        availableColors: ["#3D3C3A", "#808080"],
        itemImageUrl: "/images/test/iphone14.png",
        memory: ["256GB", "512GB", "1TB", "2TB"],
        brand: "Apple",
    },
    {
        id: '4',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '5',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '6',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '7',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        brand: 'Apple',
    },
    {
        id: '8',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '9',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        brand: 'Apple',
    },
    {
        id: '10',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        brand: 'Apple',
    },
    {
        id: '11',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],

        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '12',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        brand: 'Apple',
        memory: ["256GB", "512GB", "1TB", "2TB"],

    },
    {
        id: '13',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        memory: ["256GB", "512GB", "1TB", "2TB"],
        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '14',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        memory: ["256GB", "512GB", "1TB", "2TB"],
        name: 'Apple iPhone 14 Pro Max',
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        brand: 'Apple',
    },
    {
        id: '15',
        availableColors: ['#5B5B5B', '#AB83FF', '#6D9FFF', '#FF6363'],
        name: 'Apple iPhone 14 Pro Max',
        memory: ["256GB", "512GB", "1TB", "2TB"],
        description: '128GB Deep Purple (MQ9T3RX/A)',
        itemImageUrl: '/images/test/iphone14.png',
        price: '1699.99',
        brand: 'Apple',
    },
];
export default mockProducts;